# Generated by Django 5.2.14 on 2026-06-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveIntegerField(default=9, verbose_name='章節')),
                ('text', models.TextField(verbose_name='題目')),
                ('explanation', models.TextField(blank=True, verbose_name='解析')),
                ('difficulty', models.CharField(choices=[('easy', '易'), ('medium', '中'), ('hard', '難')], default='medium', max_length=10, verbose_name='難易度')),
                ('is_original', models.BooleanField(default=False, verbose_name='是否為自行設計新題')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='選項內容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否為正確答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='題目')),
            ],
            options={
                'verbose_name': '選項',
                'verbose_name_plural': '選項',
            },
        ),
    ]
